# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'prototype1.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QListView, QPushButton, QScrollArea,
    QSizePolicy, QStackedWidget, QTextEdit, QVBoxLayout,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(807, 601)
        Form.setMinimumSize(QSize(680, 480))
        self.MainPages = QStackedWidget(Form)
        self.MainPages.setObjectName(u"MainPages")
        self.MainPages.setGeometry(QRect(120, 50, 581, 461))
        self.pageLogin = QWidget()
        self.pageLogin.setObjectName(u"pageLogin")
        self.loginConfirmBtn = QPushButton(self.pageLogin)
        self.loginConfirmBtn.setObjectName(u"loginConfirmBtn")
        self.loginConfirmBtn.setGeometry(QRect(310, 320, 151, 41))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.loginConfirmBtn.setFont(font)
        self.label_2 = QLabel(self.pageLogin)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(250, 60, 71, 41))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        self.label_2.setFont(font1)
        self.loginRegisterBtn = QPushButton(self.pageLogin)
        self.loginRegisterBtn.setObjectName(u"loginRegisterBtn")
        self.loginRegisterBtn.setGeometry(QRect(120, 320, 151, 41))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(True)
        self.loginRegisterBtn.setFont(font2)
        self.loginUsername = QTextEdit(self.pageLogin)
        self.loginUsername.setObjectName(u"loginUsername")
        self.loginUsername.setGeometry(QRect(120, 160, 331, 31))
        self.loginPassword = QTextEdit(self.pageLogin)
        self.loginPassword.setObjectName(u"loginPassword")
        self.loginPassword.setGeometry(QRect(120, 240, 331, 31))
        self.label_9 = QLabel(self.pageLogin)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(120, 140, 81, 16))
        font3 = QFont()
        font3.setPointSize(12)
        self.label_9.setFont(font3)
        self.label_10 = QLabel(self.pageLogin)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(120, 220, 81, 16))
        self.label_10.setFont(font3)
        self.MainPages.addWidget(self.pageLogin)
        self.pageRegister = QWidget()
        self.pageRegister.setObjectName(u"pageRegister")
        self.label_3 = QLabel(self.pageRegister)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(240, 40, 111, 41))
        self.label_3.setFont(font1)
        self.registerConfirmBtn = QPushButton(self.pageRegister)
        self.registerConfirmBtn.setObjectName(u"registerConfirmBtn")
        self.registerConfirmBtn.setGeometry(QRect(320, 360, 141, 31))
        self.registerConfirmBtn.setFont(font)
        self.registerLoginBtn = QPushButton(self.pageRegister)
        self.registerLoginBtn.setObjectName(u"registerLoginBtn")
        self.registerLoginBtn.setGeometry(QRect(110, 360, 141, 31))
        self.registerLoginBtn.setFont(font)
        self.registerUsername = QTextEdit(self.pageRegister)
        self.registerUsername.setObjectName(u"registerUsername")
        self.registerUsername.setGeometry(QRect(110, 140, 351, 31))
        self.registerPassword = QTextEdit(self.pageRegister)
        self.registerPassword.setObjectName(u"registerPassword")
        self.registerPassword.setGeometry(QRect(110, 220, 351, 31))
        self.registerConfirmPassword = QTextEdit(self.pageRegister)
        self.registerConfirmPassword.setObjectName(u"registerConfirmPassword")
        self.registerConfirmPassword.setGeometry(QRect(110, 300, 351, 31))
        self.label_11 = QLabel(self.pageRegister)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(110, 120, 81, 16))
        self.label_11.setFont(font3)
        self.label_12 = QLabel(self.pageRegister)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(110, 200, 81, 16))
        self.label_12.setFont(font3)
        self.label_13 = QLabel(self.pageRegister)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(110, 280, 141, 16))
        self.label_13.setFont(font3)
        self.MainPages.addWidget(self.pageRegister)
        self.pageHome = QWidget()
        self.pageHome.setObjectName(u"pageHome")
        self.verticalLayoutWidget = QWidget(self.pageHome)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 0, 581, 461))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinimumSize)
        self.homeUserName = QLabel(self.verticalLayoutWidget)
        self.homeUserName.setObjectName(u"homeUserName")
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        self.homeUserName.setFont(font4)

        self.horizontalLayout.addWidget(self.homeUserName)

        self.homeSearchBar = QLineEdit(self.verticalLayoutWidget)
        self.homeSearchBar.setObjectName(u"homeSearchBar")

        self.horizontalLayout.addWidget(self.homeSearchBar)

        self.homeLogoutBtn = QPushButton(self.verticalLayoutWidget)
        self.homeLogoutBtn.setObjectName(u"homeLogoutBtn")
        font5 = QFont()
        font5.setBold(True)
        self.homeLogoutBtn.setFont(font5)

        self.horizontalLayout.addWidget(self.homeLogoutBtn)

        self.homeEditBtn = QPushButton(self.verticalLayoutWidget)
        self.homeEditBtn.setObjectName(u"homeEditBtn")
        self.homeEditBtn.setFont(font5)

        self.horizontalLayout.addWidget(self.homeEditBtn)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.scrollArea = QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setSizeIncrement(QSize(1, 1))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidget = QWidget()
        self.scrollAreaWidget.setObjectName(u"scrollAreaWidget")
        self.scrollAreaWidget.setGeometry(QRect(0, 0, 577, 425))
        self.scrollArea.setWidget(self.scrollAreaWidget)

        self.verticalLayout.addWidget(self.scrollArea)

        self.MainPages.addWidget(self.pageHome)
        self.pageCreateRoom = QWidget()
        self.pageCreateRoom.setObjectName(u"pageCreateRoom")
        self.createRoomCancleBtn = QPushButton(self.pageCreateRoom)
        self.createRoomCancleBtn.setObjectName(u"createRoomCancleBtn")
        self.createRoomCancleBtn.setGeometry(QRect(140, 300, 141, 31))
        self.label_4 = QLabel(self.pageCreateRoom)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(210, 60, 171, 61))
        self.label_4.setFont(font1)
        self.createRoomConfirmBtn = QPushButton(self.pageCreateRoom)
        self.createRoomConfirmBtn.setObjectName(u"createRoomConfirmBtn")
        self.createRoomConfirmBtn.setGeometry(QRect(330, 300, 141, 31))
        self.createRoomName = QTextEdit(self.pageCreateRoom)
        self.createRoomName.setObjectName(u"createRoomName")
        self.createRoomName.setGeometry(QRect(140, 163, 331, 31))
        self.createRoomDescription = QTextEdit(self.pageCreateRoom)
        self.createRoomDescription.setObjectName(u"createRoomDescription")
        self.createRoomDescription.setGeometry(QRect(140, 230, 331, 31))
        self.label_7 = QLabel(self.pageCreateRoom)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(140, 140, 101, 16))
        self.label_7.setFont(font3)
        self.label_8 = QLabel(self.pageCreateRoom)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(140, 210, 91, 16))
        self.label_8.setFont(font3)
        self.MainPages.addWidget(self.pageCreateRoom)
        self.pageRoom = QWidget()
        self.pageRoom.setObjectName(u"pageRoom")
        self.roomChatBtn = QPushButton(self.pageRoom)
        self.roomChatBtn.setObjectName(u"roomChatBtn")
        self.roomChatBtn.setGeometry(QRect(10, 80, 75, 24))
        self.label = QLabel(self.pageRoom)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 101, 31))
        self.label.setFont(font1)
        self.roomCallBtn = QPushButton(self.pageRoom)
        self.roomCallBtn.setObjectName(u"roomCallBtn")
        self.roomCallBtn.setGeometry(QRect(10, 140, 75, 24))
        self.roomWorkshopBtn = QPushButton(self.pageRoom)
        self.roomWorkshopBtn.setObjectName(u"roomWorkshopBtn")
        self.roomWorkshopBtn.setGeometry(QRect(10, 200, 75, 24))
        self.SubPages = QStackedWidget(self.pageRoom)
        self.SubPages.setObjectName(u"SubPages")
        self.SubPages.setGeometry(QRect(120, 60, 451, 391))
        self.pageChat = QWidget()
        self.pageChat.setObjectName(u"pageChat")
        self.label_5 = QLabel(self.pageChat)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(200, 10, 41, 16))
        font6 = QFont()
        font6.setPointSize(14)
        font6.setBold(True)
        self.label_5.setFont(font6)
        self.chatSendTextArea = QScrollArea(self.pageChat)
        self.chatSendTextArea.setObjectName(u"chatSendTextArea")
        self.chatSendTextArea.setGeometry(QRect(10, 340, 431, 41))
        self.chatSendTextArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 429, 39))
        self.chatSendTextData = QTextEdit(self.scrollAreaWidgetContents)
        self.chatSendTextData.setObjectName(u"chatSendTextData")
        self.chatSendTextData.setGeometry(QRect(0, 0, 431, 41))
        self.chatSendTextConfirmBtn = QPushButton(self.scrollAreaWidgetContents)
        self.chatSendTextConfirmBtn.setObjectName(u"chatSendTextConfirmBtn")
        self.chatSendTextConfirmBtn.setGeometry(QRect(400, 10, 21, 21))
        self.chatSendTextConfirmBtn.setFont(font2)
        self.chatSendTextArea.setWidget(self.scrollAreaWidgetContents)
        self.chatHistoryArea = QScrollArea(self.pageChat)
        self.chatHistoryArea.setObjectName(u"chatHistoryArea")
        self.chatHistoryArea.setGeometry(QRect(10, 40, 431, 281))
        self.chatHistoryArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 429, 279))
        self.chatHistoryArea.setWidget(self.scrollAreaWidgetContents_2)
        self.SubPages.addWidget(self.pageChat)
        self.pageCall = QWidget()
        self.pageCall.setObjectName(u"pageCall")
        self.enterOrLeaveCall = QPushButton(self.pageCall)
        self.enterOrLeaveCall.setObjectName(u"enterOrLeaveCall")
        self.enterOrLeaveCall.setGeometry(QRect(180, 180, 75, 24))
        self.SubPages.addWidget(self.pageCall)
        self.pageWorkShop = QWidget()
        self.pageWorkShop.setObjectName(u"pageWorkShop")
        self.workshopCodeSpace = QTextEdit(self.pageWorkShop)
        self.workshopCodeSpace.setObjectName(u"workshopCodeSpace")
        self.workshopCodeSpace.setGeometry(QRect(20, 40, 421, 341))
        self.label_6 = QLabel(self.pageWorkShop)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 10, 91, 21))
        self.label_6.setFont(font)
        self.workshopRunBtn = QPushButton(self.pageWorkShop)
        self.workshopRunBtn.setObjectName(u"workshopRunBtn")
        self.workshopRunBtn.setGeometry(QRect(120, 10, 75, 24))
        self.workshopRunBtn.setFont(font)
        self.SubPages.addWidget(self.pageWorkShop)
        self.pageMember = QWidget()
        self.pageMember.setObjectName(u"pageMember")
        self.listView = QListView(self.pageMember)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(10, 10, 431, 371))
        self.SubPages.addWidget(self.pageMember)
        self.roomMemberBtn = QPushButton(self.pageRoom)
        self.roomMemberBtn.setObjectName(u"roomMemberBtn")
        self.roomMemberBtn.setGeometry(QRect(10, 270, 75, 24))
        self.roomName = QLabel(self.pageRoom)
        self.roomName.setObjectName(u"roomName")
        self.roomName.setGeometry(QRect(110, 0, 421, 31))
        self.roomName.setFont(font1)
        self.label_14 = QLabel(self.pageRoom)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 40, 49, 16))
        self.label_14.setFont(font2)
        self.roomCode = QLabel(self.pageRoom)
        self.roomCode.setObjectName(u"roomCode")
        self.roomCode.setGeometry(QRect(70, 40, 141, 16))
        self.roomCode.setFont(font2)
        self.MainPages.addWidget(self.pageRoom)

        self.retranslateUi(Form)

        self.MainPages.setCurrentIndex(2)
        self.SubPages.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.loginConfirmBtn.setText(QCoreApplication.translate("Form", u"Login", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Login", None))
        self.loginRegisterBtn.setText(QCoreApplication.translate("Form", u"Register", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Username :", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Password : ", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Register", None))
        self.registerConfirmBtn.setText(QCoreApplication.translate("Form", u"Register", None))
        self.registerLoginBtn.setText(QCoreApplication.translate("Form", u"Login", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Username :", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Password : ", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Confirm Password :", None))
        self.homeUserName.setText(QCoreApplication.translate("Form", u"Name Surname", None))
        self.homeLogoutBtn.setText(QCoreApplication.translate("Form", u"logout", None))
        self.homeEditBtn.setText(QCoreApplication.translate("Form", u"Edit", None))
        self.createRoomCancleBtn.setText(QCoreApplication.translate("Form", u"Cancle", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Create Room", None))
        self.createRoomConfirmBtn.setText(QCoreApplication.translate("Form", u"Create", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Room Name :", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Description :", None))
        self.roomChatBtn.setText(QCoreApplication.translate("Form", u"Chat", None))
        self.label.setText(QCoreApplication.translate("Form", u"Room : ", None))
        self.roomCallBtn.setText(QCoreApplication.translate("Form", u"Call", None))
        self.roomWorkshopBtn.setText(QCoreApplication.translate("Form", u"Workshop", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Chat", None))
        self.chatSendTextConfirmBtn.setText(QCoreApplication.translate("Form", u"<", None))
        self.enterOrLeaveCall.setText(QCoreApplication.translate("Form", u"Enter Call", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"WorkSpace", None))
        self.workshopRunBtn.setText(QCoreApplication.translate("Form", u"Run", None))
        self.roomMemberBtn.setText(QCoreApplication.translate("Form", u"Members", None))
        self.roomName.setText(QCoreApplication.translate("Form", u"Place Holder", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"Code : ", None))
        self.roomCode.setText(QCoreApplication.translate("Form", u"code place Holder", None))
    # retranslateUi

